# Generated by Django 4.2 on 2023-06-04 21:27

import django.core.validators
from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_city_alter_customuser_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=phone_field.models.PhoneField(max_length=31, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='کد پستی'),
        ),
    ]
