# Generated by Django 4.2 on 2023-06-05 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(error_messages={'invalid': 'لطفا یک شماره تماس معتبر وارد نمایید'}, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='09{0-9}'), django.core.validators.MinLengthValidator(11)], verbose_name='شماره موبایل'),
        ),
    ]
