# Generated by Django 4.2 on 2023-06-05 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(blank=True, error_messages={'invalid': 'لطفا یک کد ملی معتبر وارد نمایید'}, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{10}')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(error_messages={'invalid': 'لطفا یک شماره موبایل معتبر وارد نمایید\nمانند 09123456789'}, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='09[0-9]{9}')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(error_messages={'invalid': 'لطفا یک کد پستی معتبر وارد نمایید'}, max_length=10, validators=[django.core.validators.RegexValidator(regex='\\d{10}')], verbose_name='کد پستی'),
        ),
    ]
