# Generated by Django 4.2 on 2023-07-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('date_joined',), 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
