# Generated by Django 4.2 on 2023-06-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_name_category_slug_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='دسته_بندی',
        ),
    ]
