# Generated by Django 4.2 on 2023-06-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_category_دسته_بندی'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='دسته_بندی',
            new_name='Category',
        ),
    ]
