# Generated by Django 4.2 on 2023-06-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_image_alter_picture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='images',
        ),
    ]
