# Generated by Django 4.2 on 2023-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210802_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
