# Generated by Django 4.2 on 2023-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شناسه پرداخت'),
        ),
    ]
